# Generated by Django 6.0.2 on 2026-02-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_full_name_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
