# Generated by Django 6.0.2 on 2026-03-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_payment_paymen_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='provider_id',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
